#!/usr/bin/env python3
"""
Assemble a template (mock-up) from its shotlist: every slot gets the best clip available.

  assemble.py templates/A_teaser --status        which slots are filled, with what
  assemble.py templates/A_teaser                 build out/A_teaser_preview.mp4
  assemble.py templates/A_teaser --publish       ... and print a link that plays in the browser
  assemble.py templates/A_teaser --placeholders  (re)render the grey placeholder clips

Source per slot, first match wins:
  slots/<id>.mp4        generated today (vg.py submit --slot templates/A_teaser/<id>)
  reserves/<id>.mp4     pre-generated by the facilitators, used if an API is down
  placeholders/<id>.mp4 grey card naming the slot
  a plain colour clip   if even the placeholder is missing
Real-footage slots read their file from input/real/. Card slots are drawn with ffmpeg drawtext.
Standard library + ffmpeg only; no ffprobe needed.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import vg  # noqa: E402

REPO = vg.REPO


def ffmpeg() -> str:
    exe = os.environ.get("FFMPEG") or shutil.which("ffmpeg")
    if not exe and (Path.home() / ".local" / "bin" / "ffmpeg").exists():
        exe = str(Path.home() / ".local" / "bin" / "ffmpeg")
    if not exe:
        try:
            import imageio_ffmpeg  # fallback installed by scripts/setup_cloud.sh
            exe = imageio_ffmpeg.get_ffmpeg_exe()
        except ImportError:
            pass
    if not exe:
        vg.die("ffmpeg not found. Run: bash scripts/setup_cloud.sh")
    return exe


def has_filter(name: str) -> bool:
    r = subprocess.run([ffmpeg(), "-hide_banner", "-filters"], capture_output=True, text=True)
    return re.search(rf"^\s*\S+\s+{name}\s", r.stdout, re.M) is not None


def probe(path: Path) -> tuple[float, bool]:
    """(duration in seconds, has audio) from ffmpeg's own banner."""
    r = subprocess.run([ffmpeg(), "-hide_banner", "-i", str(path)], capture_output=True, text=True)
    m = re.search(r"Duration: (\d+):(\d+):([\d.]+)", r.stderr)
    dur = int(m.group(1)) * 3600 + int(m.group(2)) * 60 + float(m.group(3)) if m else 0.0
    return dur, " Audio:" in r.stderr


def run(cmd):
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode:
        raise RuntimeError("ffmpeg failed:\n" + r.stderr[-1200:])


def load(template: Path) -> dict:
    f = template / "shotlist.json"
    if not f.exists():
        vg.die(f"no shotlist.json in {template}")
    return json.loads(f.read_text())


def source(template: Path, s: dict) -> tuple[Path | None, str]:
    if s["type"] == "real":
        f = REPO / s["file"]
        if f.exists():
            return f, "real footage"
    for where in ("slots", "reserves", "placeholders"):
        f = template / where / f"{s['id']}.mp4"
        if f.exists():
            return f, {"slots": "generated", "reserves": "reserve", "placeholders": "placeholder"}[where]
    return None, "empty"


def esc_path(p: Path) -> str:
    return str(p).replace("\\", "/").replace(":", r"\:").replace("'", r"\'")


def font_opt() -> str:
    for f in (os.environ.get("VG_FONT"), "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
              "/System/Library/Fonts/Helvetica.ttc", "/Library/Fonts/Arial.ttf"):
        if f and Path(f).exists():
            return f"fontfile='{esc_path(Path(f))}'"
    return "font='Sans'"


def text_layers(tmp: Path, lines: list, w: int, h: int, fg: str, big: int, small: int, y0: float) -> list:
    """drawtext filters, one per line, text read from files so nothing needs escaping."""
    out = []
    y = int(h * y0)
    for i, line in enumerate(lines):
        tf = tmp / f"line_{abs(hash((line, i)))}.txt"
        tf.write_text(line)
        size = big if i == 0 else small
        out.append(f"drawtext={font_opt()}:textfile='{esc_path(tf)}':fontcolor={fg}:fontsize={size}"
                   f":x=(w-text_w)/2:y={y}")
        y += int(size * 1.5)
    return out


def caption_layer(tmp: Path, text: str, w: int, h: int) -> str:
    tf = tmp / f"cap_{abs(hash(text))}.txt"
    tf.write_text(text)
    size = int(h * 0.045)
    return (f"drawtext={font_opt()}:textfile='{esc_path(tf)}':fontcolor=white:fontsize={size}:box=1:"
            f"boxcolor=black@0.55:boxborderw={int(size * 0.5)}:x=(w-text_w)/2:y=h-text_h-{int(h * 0.09)}")


def render_card(out: Path, lines: list, dur: float, w: int, h: int, fps: int, bg: str, fg: str, tmp: Path):
    vf = ",".join(text_layers(tmp, lines, w, h, fg, int(h * 0.075), int(h * 0.04), 0.40)) or "null"
    run([ffmpeg(), "-y", "-f", "lavfi", "-i", f"color=c={bg}:s={w}x{h}:r={fps}:d={dur}",
         "-f", "lavfi", "-i", "anullsrc=r=48000:cl=stereo", "-t", str(dur), "-vf", vf,
         "-c:v", "libx264", "-preset", "veryfast", "-crf", "20", "-pix_fmt", "yuv420p",
         "-c:a", "aac", "-b:a", "128k", "-shortest", str(out)])


def segment(src: Path | None, out: Path, s: dict, sl: dict, tmp: Path, drawtext: bool, kind: str = ""):
    w, h = sl["size"]
    fps = sl.get("fps", 25)
    dur = float(s["dur"])
    if s["type"] == "card" and drawtext:
        card = sl.get("card_style", {})
        render_card(out, s["lines"], dur, w, h, fps, card.get("bg", "0x14213d"), card.get("fg", "white"), tmp)
        return
    if src is None:
        run([ffmpeg(), "-y", "-f", "lavfi", "-i", f"color=c=0x3a3a3a:s={w}x{h}:r={fps}:d={dur}",
             "-f", "lavfi", "-i", "anullsrc=r=48000:cl=stereo", "-t", str(dur),
             "-c:v", "libx264", "-preset", "veryfast", "-pix_fmt", "yuv420p", "-c:a", "aac", "-shortest", str(out)])
        return
    length, audio = probe(src)
    # trim_start belongs to the real footage; a placeholder standing in for it starts at 0
    start = float(s.get("trim_start", 0)) if kind == "real footage" else 0.0
    take = min(dur, max(length - start, 0.1)) if length else dur
    vf = [f"scale={w}:{h}:force_original_aspect_ratio=decrease", f"pad={w}:{h}:(ow-iw)/2:(oh-ih)/2", "setsar=1", f"fps={fps}"]
    if take < dur:
        vf.append(f"tpad=stop_mode=clone:stop_duration={dur - take:.3f}")
    if s.get("caption") and drawtext:
        vf.append(caption_layer(tmp, s["caption"], w, h))
    cmd = [ffmpeg(), "-y", "-ss", f"{start:.3f}", "-i", str(src)]
    if not audio:
        cmd += ["-f", "lavfi", "-i", "anullsrc=r=48000:cl=stereo"]
    cmd += ["-t", f"{dur:.3f}", "-vf", ",".join(vf), "-map", "0:v:0", "-map", "0:a:0" if audio else "1:a:0",
            "-af", f"apad,afade=t=in:d=0.04,afade=t=out:st={max(dur - 0.06, 0):.3f}:d=0.06",
            "-c:v", "libx264", "-preset", "veryfast", "-crf", "20", "-pix_fmt", "yuv420p",
            "-c:a", "aac", "-ar", "48000", "-ac", "2", "-b:a", "160k", str(out)]
    run(cmd)


def status(template: Path, sl: dict):
    print(f"  {sl['title']} · {sl['size'][0]}x{sl['size'][1]} · {sum(float(s['dur']) for s in sl['slots']):.0f} s")
    for fr in sl.get("frames", []):
        f = REPO / fr["out"]
        print(f"  {'✓' if f.exists() else '·'} frame  {fr['id']:12} {fr['out']}")
    for s in sl["slots"]:
        src, kind = source(template, s)
        model = s.get("model", s["type"])
        mark = {"generated": "✓", "real footage": "✓", "reserve": "~", "placeholder": "·", "empty": "·"}[kind]
        if s["type"] == "card":
            kind = "drawn"
            mark = "✓"
        print(f"  {mark} {s['id']:5} {model:9} {float(s['dur']):4.1f} s  {kind:12} {s.get('purpose', '')}")
    est = sum(vg.estimate_usd(vg.load_model(s["model"]), s.get("gen_dur", int(s["dur"]))) for s in sl["slots"] if s.get("model"))
    est += sum(vg.load_model("image")["pricing"]["usd_per_image"] for _ in sl.get("frames", []))
    print(f"  filling every slot once costs about {vg.fmt_money(est)}")


def placeholders(template: Path, sl: dict):
    w, h = sl["size"]
    fps = sl.get("fps", 25)
    (template / "placeholders").mkdir(exist_ok=True)
    with tempfile.TemporaryDirectory() as t:
        for s in sl["slots"]:
            if s["type"] == "card":
                lines = s["lines"]
                bg = sl.get("card_style", {}).get("bg", "0x14213d")
            else:
                model = vg.load_model(s["model"])["name"] if s.get("model") else "Real footage"
                lines = [f"{s['id']} · {model} · {float(s['dur']):g} s", s.get("purpose", "")]
                bg = "0x3a3a3a"
            render_card(template / "placeholders" / f"{s['id']}.mp4", lines, float(s["dur"]), w, h, fps, bg, "white", Path(t))
            print(f"  ✓ placeholders/{s['id']}.mp4")


def build(template: Path, sl: dict, publish: bool):
    drawtext = has_filter("drawtext")
    if not drawtext:
        print("  · this ffmpeg has no drawtext: cards use their placeholder, captions are skipped")
    out = vg.OUT / f"{template.name}_preview.mp4"
    out.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory() as t:
        tmp = Path(t)
        parts = []
        for i, s in enumerate(sl["slots"]):
            src, kind = source(template, s)
            seg = tmp / f"{i:02d}_{s['id']}.mp4"
            segment(src, seg, s, sl, tmp, drawtext, kind)
            got, _ = probe(seg)
            if abs(got - float(s["dur"])) > 0.15:
                print(f"  ⚠ {s['id']}: segment is {got:.2f} s, shotlist says {s['dur']} s")
            parts.append(seg)
            print(f"  · {s['id']:5} {kind if s['type'] != 'card' else 'card'}")
        lst = tmp / "list.txt"
        lst.write_text("".join(f"file '{p}'\n" for p in parts))
        run([ffmpeg(), "-y", "-f", "concat", "-safe", "0", "-i", str(lst), "-c", "copy", "-movflags", "+faststart", str(out)])
    dur, _ = probe(out)
    print(f"  ✓ {out.relative_to(REPO)} · {dur:.1f} s")
    if publish:
        if not vg.s3_ready():
            vg.die("bucket is not configured (VG_S3_*); the preview stays in out/")
        print(f"    watch: {vg.publish(out)}")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("template")
    ap.add_argument("--status", action="store_true")
    ap.add_argument("--placeholders", action="store_true")
    ap.add_argument("--publish", action="store_true")
    a = ap.parse_args()
    template = (REPO / a.template) if not Path(a.template).is_absolute() else Path(a.template)
    sl = load(template)
    try:
        if a.status:
            status(template, sl)
        elif a.placeholders:
            placeholders(template, sl)
        else:
            build(template, sl, a.publish)
    except RuntimeError as e:
        vg.die(str(e))


if __name__ == "__main__":
    main()
