#!/usr/bin/env python3
"""
Assemble a template (mock-up) from its shotlist: every slot gets the best clip available.

  assemble.py templates/A_teaser --status        which slots are filled, with what
  assemble.py templates/A_teaser                 build out/A_teaser_preview.mp4
  assemble.py templates/A_teaser --publish       ... and print a link that plays in the browser
  assemble.py templates/A_teaser --placeholders  (re)render the grey placeholder clips
  assemble.py templates/A_teaser --takes         every take of every slot, and which one is in use
  assemble.py templates/A_teaser --compare s1    the takes of s1 side by side, to choose
  assemble.py templates/A_teaser --use s1 t2     put take t2 into slot s1
  assemble.py templates/A_teaser --card          a still of the end card, to iterate its design

Source per slot, first match wins:
  slots/<id>.mp4        generated today (vg.py submit --slot templates/A_teaser/<id>)
  reserves/<id>.mp4     pre-generated by the facilitators, used if an API is down
  placeholders/<id>.mp4 grey card naming the slot
  a plain colour clip   if even the placeholder is missing
Real-footage slots read their file from input/real/. Card slots are drawn with ffmpeg drawtext.
Standard library + ffmpeg only; no ffprobe needed.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import vg  # noqa: E402

REPO = vg.REPO


def ffmpeg() -> str:
    exe = os.environ.get("FFMPEG") or shutil.which("ffmpeg")
    if not exe and (Path.home() / ".local" / "bin" / "ffmpeg").exists():
        exe = str(Path.home() / ".local" / "bin" / "ffmpeg")
    if not exe:
        try:
            import imageio_ffmpeg  # fallback installed by scripts/setup_cloud.sh
            exe = imageio_ffmpeg.get_ffmpeg_exe()
        except ImportError:
            pass
    if not exe:
        vg.die("ffmpeg not found. Run: bash scripts/setup_cloud.sh")
    return exe


def has_filter(name: str) -> bool:
    r = subprocess.run([ffmpeg(), "-hide_banner", "-filters"], capture_output=True, text=True)
    return re.search(rf"^\s*\S+\s+{name}\s", r.stdout, re.M) is not None


def probe(path: Path) -> tuple[float, bool]:
    """(duration in seconds, has audio) from ffmpeg's own banner."""
    r = subprocess.run([ffmpeg(), "-hide_banner", "-i", str(path)], capture_output=True, text=True)
    m = re.search(r"Duration: (\d+):(\d+):([\d.]+)", r.stderr)
    dur = int(m.group(1)) * 3600 + int(m.group(2)) * 60 + float(m.group(3)) if m else 0.0
    return dur, " Audio:" in r.stderr


def run(cmd):
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode:
        raise RuntimeError("ffmpeg failed:\n" + r.stderr[-1200:])


def load(template: Path) -> dict:
    f = template / "shotlist.json"
    if not f.exists():
        vg.die(f"no shotlist.json in {template}")
    return json.loads(f.read_text())


def source(template: Path, s: dict) -> tuple[Path | None, str]:
    if s["type"] == "real":
        f = REPO / s["file"]
        if f.exists():
            return f, "real footage"
    for where in ("slots", "reserves", "placeholders"):
        f = template / where / f"{s['id']}.mp4"
        if f.exists():
            return f, {"slots": "generated", "reserves": "reserve", "placeholders": "placeholder"}[where]
    return None, "empty"


def esc_path(p: Path) -> str:
    return str(p).replace("\\", "/").replace(":", r"\:").replace("'", r"\'")


def font_opt() -> str:
    for f in (os.environ.get("VG_FONT"), "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
              "/System/Library/Fonts/Helvetica.ttc", "/Library/Fonts/Arial.ttf"):
        if f and Path(f).exists():
            return f"fontfile='{esc_path(Path(f))}'"
    return "font='Sans'"


def text_layers(tmp: Path, lines: list, w: int, h: int, fg: str, big: int, small: int, y0: float) -> list:
    """drawtext filters, one per line, text read from files so nothing needs escaping."""
    out = []
    y = int(h * y0)
    for i, line in enumerate(lines):
        tf = tmp / f"line_{abs(hash((line, i)))}.txt"
        tf.write_text(line)
        size = big if i == 0 else small
        out.append(f"drawtext={font_opt()}:textfile='{esc_path(tf)}':fontcolor={fg}:fontsize={size}"
                   f":x=(w-text_w)/2:y={y}")
        y += int(size * 1.5)
    return out


def caption_layer(tmp: Path, text: str, w: int, h: int) -> str:
    tf = tmp / f"cap_{abs(hash(text))}.txt"
    tf.write_text(text)
    size = int(h * 0.045)
    return (f"drawtext={font_opt()}:textfile='{esc_path(tf)}':fontcolor=white:fontsize={size}:box=1:"
            f"boxcolor=black@0.55:boxborderw={int(size * 0.5)}:x=(w-text_w)/2:y=h-text_h-{int(h * 0.09)}")


def render_card(out: Path, lines: list, dur: float, w: int, h: int, fps: int, bg: str, fg: str, tmp: Path):
    vf = ",".join(text_layers(tmp, lines, w, h, fg, int(h * 0.075), int(h * 0.04), 0.40)) or "null"
    run([ffmpeg(), "-y", "-f", "lavfi", "-i", f"color=c={bg}:s={w}x{h}:r={fps}:d={dur}",
         "-f", "lavfi", "-i", "anullsrc=r=48000:cl=stereo", "-t", str(dur), "-vf", vf,
         "-c:v", "libx264", "-preset", "veryfast", "-crf", "20", "-pix_fmt", "yuv420p",
         "-c:a", "aac", "-b:a", "128k", "-shortest", str(out)])


AI_LABEL = "Einige Szenen wurden mit KI erstellt."


def card_options(s: dict, sl: dict) -> dict:
    """Card settings: the template's card_style, overridden by the card slot's own fields."""
    o = {"style": "solid", "bg": "0x14213d", "fg": "white", "size": "m", "align": "center", "ai_label": True}
    o.update(sl.get("card_style", {}))
    o.update({k: v for k, v in s.items() if k in ("style", "bg", "fg", "size", "align", "logo", "logo_pos", "image",
                                                  "freeze_from", "font", "ai_label")})
    return o


def freeze_source(template: Path, sl: dict, card_id: str, wanted: str | None):
    """The clip whose last frame becomes the card background: the named slot, else the last clip before the card."""
    ids = [x["id"] for x in sl["slots"]]
    order = [wanted] if wanted else list(reversed(ids[:ids.index(card_id)]))
    for sid in order:
        slot = next((x for x in sl["slots"] if x["id"] == sid), None)
        if slot and slot["type"] != "card":
            src, kind = source(template, slot)
            if src is not None:
                return src
    return None


def render_custom_card(out: Path, s: dict, sl: dict, template: Path, tmp: Path):
    o = card_options(s, sl)
    w, h = sl["size"]
    fps = sl.get("fps", 25)
    dur = float(s["dur"])
    ff = ffmpeg()
    scale = {"s": 0.8, "m": 1.0, "l": 1.3}.get(o["size"], 1.0)
    cmd = [ff, "-y"]
    style = o["style"]
    if style == "freeze":
        src = freeze_source(template, sl, s["id"], o.get("freeze_from"))
        if src is None:
            style = "solid"
        else:
            still = tmp / "freeze.png"
            run([ff, "-y", "-sseof", "-0.3", "-i", str(src), "-frames:v", "1", str(still)])
            cmd += ["-loop", "1", "-t", str(dur), "-i", str(still)]
    if style == "image":
        img = REPO / o["image"] if o.get("image") else None
        if img and img.exists():
            cmd += ["-loop", "1", "-t", str(dur), "-i", str(img)]
        else:
            style = "solid"
    if style == "solid":
        cmd += ["-f", "lavfi", "-i", f"color=c={o['bg']}:s={w}x{h}:r={fps}:d={dur}"]
    cmd += ["-f", "lavfi", "-i", "anullsrc=r=48000:cl=stereo"]
    chain = f"[0:v]scale={w}:{h}:force_original_aspect_ratio=increase,crop={w}:{h},setsar=1,fps={fps}"
    if style == "freeze":
        chain += ",boxblur=24:2,eq=brightness=-0.28:saturation=0.8"
    elif style == "image":
        chain += ",eq=brightness=-0.18"
    chain += "[bg]"
    chains, last = [chain], "bg"
    logo = REPO / o["logo"] if o.get("logo") else None
    if logo and logo.exists():
        cmd += ["-i", str(logo)]
        li = 2
        lh = int(h * 0.12 * scale)
        pos = "x=W-w-48:y=48" if o.get("logo_pos") == "corner" else "x=(W-w)/2:y=H*0.18"
        chains.append(f"[{li}:v]scale=-1:{lh}[lg]")
        chains.append(f"[{last}][lg]overlay={pos}[wl]")
        last = "wl"
    font = f"fontfile='{esc_path(REPO / o['font'])}'" if o.get("font") and (REPO / o["font"]).exists() else font_opt()
    y0 = 0.40 if o["align"] == "center" else 0.68
    y = int(h * y0)
    alpha = "if(lt(t,0.35),t/0.35,1)"
    draws = []
    for i, line in enumerate(s.get("lines", [])):
        tf = tmp / f"card_{i}.txt"
        tf.write_text(line)
        size = int(h * (0.08 if i == 0 else 0.042) * scale)
        draws.append(f"drawtext={font}:textfile='{esc_path(tf)}':fontcolor={o['fg']}:fontsize={size}:"
                     f"x=(w-text_w)/2:y={y}:alpha='{alpha}'")
        y += int(size * 1.45)
    if o.get("ai_label", True):
        tf = tmp / "ai_label.txt"
        tf.write_text(AI_LABEL)
        draws.append(f"drawtext={font_opt()}:textfile='{esc_path(tf)}':fontcolor={o['fg']}@0.7:fontsize={int(h * 0.022)}:"
                     f"x=(w-text_w)/2:y=h-text_h-{int(h * 0.04)}")
    chains.append(f"[{last}]" + (",".join(draws) if draws else "null") + "[v]")
    audio_index = 1
    cmd += ["-filter_complex", ";".join(chains), "-map", "[v]", "-map", f"{audio_index}:a", "-t", str(dur),
            "-c:v", "libx264", "-preset", "veryfast", "-crf", "20", "-pix_fmt", "yuv420p",
            "-c:a", "aac", "-b:a", "128k", "-shortest", str(out)]
    run(cmd)


def card_preview(template: Path, sl: dict):
    card = next((x for x in sl["slots"] if x["type"] == "card" and x["id"] == "card"), None) or \
        next((x for x in reversed(sl["slots"]) if x["type"] == "card"), None)
    if not card:
        vg.die("this template has no card")
    with tempfile.TemporaryDirectory() as t:
        tmp = Path(t)
        clip = tmp / "card.mp4"
        render_custom_card(clip, card, sl, template, tmp)
        out = vg.OUT / f"{template.name}_{card['id']}.png"
        out.parent.mkdir(parents=True, exist_ok=True)
        run([ffmpeg(), "-y", "-ss", f"{min(1.5, float(card['dur']) - 0.1):.2f}", "-i", str(clip), "-frames:v", "1", str(out)])
    o = card_options(card, sl)
    print(f"  ✓ {out.relative_to(REPO)} · style {o['style']}, text {o['fg']}, {o['align']}, size {o['size']}"
          + (f", logo {o['logo']}" if o.get("logo") else "") + (", AI label on" if o.get("ai_label", True) else ""))


def segment(src: Path | None, out: Path, s: dict, sl: dict, tmp: Path, drawtext: bool, kind: str = "",
            template: Path | None = None):
    w, h = sl["size"]
    fps = sl.get("fps", 25)
    dur = float(s["dur"])
    if s["type"] == "card" and drawtext:
        render_custom_card(out, s, sl, template or REPO, tmp)
        return
    if src is None:
        run([ffmpeg(), "-y", "-f", "lavfi", "-i", f"color=c=0x3a3a3a:s={w}x{h}:r={fps}:d={dur}",
             "-f", "lavfi", "-i", "anullsrc=r=48000:cl=stereo", "-t", str(dur),
             "-c:v", "libx264", "-preset", "veryfast", "-pix_fmt", "yuv420p", "-c:a", "aac", "-shortest", str(out)])
        return
    length, audio = probe(src)
    # trim_start belongs to the real footage; a placeholder standing in for it starts at 0
    start = float(s.get("trim_start", 0)) if kind == "real footage" else 0.0
    take = min(dur, max(length - start, 0.1)) if length else dur
    vf = [f"scale={w}:{h}:force_original_aspect_ratio=decrease", f"pad={w}:{h}:(ow-iw)/2:(oh-ih)/2", "setsar=1", f"fps={fps}"]
    if take < dur:
        vf.append(f"tpad=stop_mode=clone:stop_duration={dur - take:.3f}")
    if s.get("caption") and drawtext:
        vf.append(caption_layer(tmp, s["caption"], w, h))
    cmd = [ffmpeg(), "-y", "-ss", f"{start:.3f}", "-i", str(src)]
    if not audio:
        cmd += ["-f", "lavfi", "-i", "anullsrc=r=48000:cl=stereo"]
    cmd += ["-t", f"{dur:.3f}", "-vf", ",".join(vf), "-map", "0:v:0", "-map", "0:a:0" if audio else "1:a:0",
            "-af", f"apad,afade=t=in:d=0.04,afade=t=out:st={max(dur - 0.06, 0):.3f}:d=0.06",
            "-c:v", "libx264", "-preset", "veryfast", "-crf", "20", "-pix_fmt", "yuv420p",
            "-c:a", "aac", "-ar", "48000", "-ac", "2", "-b:a", "160k", str(out)]
    run(cmd)


def status(template: Path, sl: dict):
    print(f"  {sl['title']} · {sl['size'][0]}x{sl['size'][1]} · {sum(float(s['dur']) for s in sl['slots']):.0f} s")
    for fr in sl.get("frames", []):
        f = REPO / fr["out"]
        print(f"  {'✓' if f.exists() else '·'} frame  {fr['id']:12} {fr['out']}")
    for s in sl["slots"]:
        src, kind = source(template, s)
        model = s.get("model", s["type"])
        mark = {"generated": "✓", "real footage": "✓", "reserve": "~", "placeholder": "·", "empty": "·"}[kind]
        if s["type"] == "card":
            kind = "drawn"
            mark = "✓"
        print(f"  {mark} {s['id']:5} {model:9} {float(s['dur']):4.1f} s  {kind:12} {s.get('purpose', '')}")
        if s.get("task"):
            print(f"          task: {s['task']}")
    est = sum(vg.estimate_usd(vg.load_model(s["model"]), s.get("gen_dur", int(s["dur"]))) for s in sl["slots"] if s.get("model"))
    est += sum(vg.load_model("image")["pricing"]["usd_per_image"] for _ in sl.get("frames", []))
    print(f"  filling every slot once costs about {vg.fmt_money(est)}")


def placeholders(template: Path, sl: dict):
    w, h = sl["size"]
    fps = sl.get("fps", 25)
    (template / "placeholders").mkdir(exist_ok=True)
    with tempfile.TemporaryDirectory() as t:
        for s in sl["slots"]:
            if s["type"] == "card":
                lines = s["lines"]
                bg = sl.get("card_style", {}).get("bg", "0x14213d")
            else:
                model = vg.load_model(s["model"])["name"] if s.get("model") else "Real footage"
                lines = [f"{s['id']} · {model} · {float(s['dur']):g} s", s.get("purpose", "")]
                bg = "0x3a3a3a"
            render_card(template / "placeholders" / f"{s['id']}.mp4", lines, float(s["dur"]), w, h, fps, bg, "white", Path(t))
            print(f"  ✓ placeholders/{s['id']}.mp4")


def build(template: Path, sl: dict, publish: bool):
    drawtext = has_filter("drawtext")
    if not drawtext:
        print("  · this ffmpeg has no drawtext: cards use their placeholder, captions are skipped")
    out = vg.OUT / f"{template.name}_preview.mp4"
    out.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory() as t:
        tmp = Path(t)
        parts = []
        for i, s in enumerate(sl["slots"]):
            src, kind = source(template, s)
            seg = tmp / f"{i:02d}_{s['id']}.mp4"
            segment(src, seg, s, sl, tmp, drawtext, kind, template)
            got, _ = probe(seg)
            if abs(got - float(s["dur"])) > 0.15:
                print(f"  ⚠ {s['id']}: segment is {got:.2f} s, shotlist says {s['dur']} s")
            parts.append(seg)
            print(f"  · {s['id']:5} {kind if s['type'] != 'card' else 'card'}")
        lst = tmp / "list.txt"
        lst.write_text("".join(f"file '{p}'\n" for p in parts))
        run([ffmpeg(), "-y", "-f", "concat", "-safe", "0", "-i", str(lst), "-c", "copy", "-movflags", "+faststart", str(out)])
    dur, _ = probe(out)
    print(f"  ✓ {out.relative_to(REPO)} · {dur:.1f} s")
    if publish:
        if not vg.s3_ready():
            vg.die("bucket is not configured (VG_S3_*); the preview stays in out/")
        print(f"    watch: {vg.publish(out)}")


def takes_of(template: Path, slot: str) -> list:
    return sorted((template / "takes").glob(f"{slot}_t*.mp4"), key=lambda f: int(f.stem.rsplit("_t", 1)[1]))


def list_takes(template: Path, sl: dict):
    for s in sl["slots"]:
        if not s.get("model"):
            continue
        takes = takes_of(template, s["id"])
        mark = template / "slots" / f"{s['id']}.take"
        in_use = mark.read_text().strip() if mark.exists() else None
        names = [f"t{t.stem.rsplit('_t', 1)[1]}" + (" (in use)" if in_use == f"t{t.stem.rsplit('_t', 1)[1]}" else "")
                 for t in takes]
        print(f"  {s['id']:5} {', '.join(names) or 'none yet'}")


def use_take(template: Path, slot: str, take: str):
    n = take.lstrip("tT")
    src = template / "takes" / f"{slot}_t{n}.mp4"
    if not src.exists():
        vg.die(f"no take t{n} for {slot}; see --takes")
    (template / "slots").mkdir(exist_ok=True)
    shutil.copyfile(src, template / "slots" / f"{slot}.mp4")
    (template / "slots" / f"{slot}.take").write_text(f"t{n}")
    print(f"  ✓ {slot} now uses take t{n}. Rebuild the preview to see it in place.")


def compare(template: Path, slot: str, publish: bool):
    """All takes of one slot side by side (up to 4), labelled, muted: the picture to choose from."""
    takes = takes_of(template, slot)[-4:]
    if len(takes) < 2:
        vg.die(f"{slot} has {len(takes)} take(s); render another variation to compare")
    ff = ffmpeg()
    longest = max(probe(t)[0] for t in takes)
    w, h = 960, 540
    out = vg.OUT / f"{template.name}_{slot}_takes.mp4"
    with tempfile.TemporaryDirectory() as tmpd:
        tmp = Path(tmpd)
        chains = []
        for k, t in enumerate(takes):
            lab = tmp / f"l{k}.txt"
            lab.write_text(f"{slot} · take t{t.stem.rsplit('_t', 1)[1]}")
            d = probe(t)[0]
            chains.append(f"[{k}:v]scale={w}:{h}:force_original_aspect_ratio=decrease,pad={w}:{h}:(ow-iw)/2:(oh-ih)/2,setsar=1,fps=25,"
                          f"tpad=stop_mode=clone:stop_duration={longest - d + 0.3:.2f},"
                          f"drawtext={font_opt()}:textfile='{esc_path(lab)}':fontcolor=white:fontsize=30:box=1:"
                          f"boxcolor=black@0.6:boxborderw=10:x=16:y=16[v{k}]")
        n = len(takes)
        if n == 2:
            grid = "[v0][v1]hstack=inputs=2,pad=1920:1080:0:270:color=black[o]"
        else:
            pads = "".join(f"[v{k}]" for k in range(n))
            if n == 3:
                chains.append(f"color=c=black:s={w}x{h}:r=25:d={longest + 0.3:.2f}[v3]")
                pads += "[v3]"
            grid = f"{pads}xstack=inputs=4:layout=0_0|w0_0|0_h0|w0_h0[o]"
        cmd = [ff, "-y"]
        for t in takes:
            cmd += ["-i", str(t)]
        cmd += ["-filter_complex", ";".join(chains) + ";" + grid, "-map", "[o]", "-t", f"{longest + 0.3:.2f}", "-an",
                "-c:v", "libx264", "-preset", "veryfast", "-crf", "20", "-pix_fmt", "yuv420p", "-movflags", "+faststart", str(out)]
        run(cmd)
    print(f"  ✓ {out.relative_to(REPO)} · {n} takes of {slot} side by side")
    if publish and vg.s3_ready():
        print(f"    watch: {vg.publish(out)}")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("template")
    ap.add_argument("--status", action="store_true")
    ap.add_argument("--placeholders", action="store_true")
    ap.add_argument("--publish", action="store_true")
    ap.add_argument("--takes", action="store_true", help="list the takes of every slot")
    ap.add_argument("--use", nargs=2, metavar=("SLOT", "TAKE"), help="put a take into the slot, e.g. --use s1 t2")
    ap.add_argument("--compare", metavar="SLOT", help="the takes of one slot side by side")
    ap.add_argument("--card", action="store_true", help="a still of the end card, instant and free, to iterate its design")
    a = ap.parse_args()
    template = (REPO / a.template) if not Path(a.template).is_absolute() else Path(a.template)
    sl = load(template)
    try:
        if a.card:
            card_preview(template, sl)
        elif a.takes:
            list_takes(template, sl)
        elif a.use:
            use_take(template, *a.use)
        elif a.compare:
            compare(template, a.compare, a.publish)
        elif a.status:
            status(template, sl)
        elif a.placeholders:
            placeholders(template, sl)
        else:
            build(template, sl, a.publish)
    except RuntimeError as e:
        vg.die(str(e))


if __name__ == "__main__":
    main()
